### ISSUE TITLE
Australia: Add QLD Fuel Watch Data Source

### ISSUE THREAD

**Issue by GaryFlynn** [pantherale0/pyfuelprices#9]
Hi @pantherale0

Absolutely loved your HA integration for the UK, however now back in Australia and it looks like only WA Fuel Watch is currently supported. Would it be possible to add the data source QLD Fuel Watch to pyfuelprices and also ha-fuelprices?

https://www.fuelpricesqld.com.au/#developers

**Comment by pantherale0** [comment]
Docs for official API:

https://www.fuelpricesqld.com.au/documents/FuelPricesQLDDirectAPI(OUT)v1.6.pdf

This module doesn't currently allow passing setup parameters such as an API token to a data source. I might see if I can pull the data from one of these other apps instead, especially as some of the docs are missing / not working for me. Although I am in the UK so that might be a issue perhaps.

https://www.energyandclimate.qld.gov.au/about/initiatives/fuel-price-reporting/apps-websites

Some initial discovery,Fuel Map app uses the following endpoints:

Get stations in an area:
```
http://www.fuelmap.com.au/app/getprices2.php
```

Get all stations:
```
http://www.fuelmap.com.au/app/getstations.php
```
Get station prices
```
http://www.fuelmap.com.au/app/getstationprices2.php
```

**Comment by pantherale0** [comment]
FuelSnoop added for next version

![image](https://github.com/pantherale0/pyfuelprices/assets/7346615/1a4645b1-3f1e-4199-886c-031aac73903f)
